name: enterprise-base-linux-aws-test

on: 
  workflow_dispatch:
 
env:
  CONFIG_FILE: ${{ github.workspace }}/config/aws/arcgis-enterprise-base-linux/application.tfvars.json

jobs:
  test:
    name: Test Deployment
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/enterprise-admin-cli
    permissions:
      contents: read
      pull-requests: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref_name }}
    - name: Build Container Image
      run: |
        docker build -t enterprise-admin-cli .
    - name: Run Tests
      run: |
        DEPLOYMENT_FQDN=$(jq -r '.deployment_fqdn' $CONFIG_FILE)
        ARCGIS_ENTERPRISE_CONTEXT=portal
        ADMIN_USERNAME=$(jq -r '.admin_username' $CONFIG_FILE)
        ADMIN_PASSWORD=$(jq -r '.admin_password' $CONFIG_FILE)
        docker run enterprise-admin-cli python publish_csv.py -a https://$DEPLOYMENT_FQDN/$ARCGIS_ENTERPRISE_CONTEXT -u $ADMIN_USERNAME -p $ADMIN_PASSWORD
