name: enterprise-base-linux-aws-restore

on: 
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TERRAFORM_BACKEND_S3_BUCKET: ${{ vars.TERRAFORM_BACKEND_S3_BUCKET }}
  AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
  PYTHONPATH: ${{ github.workspace }}/aws/scripts
  CONFIG_FILE: ${{ github.workspace }}/config/aws/arcgis-enterprise-base-linux/restore.tfvars.json

concurrency:
  group: ${{ github.ref_name }}

jobs:
  restore:
    name: Restore from Backup
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: aws/arcgis-enterprise-base-linux/restore
    permissions:
      contents: read
      pull-requests: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref_name }}
    - name: Install boto3
      id: install-boto3
      run: pip install boto3
    - name: Run Terraform
      id: terraform
      run: |
        SITE_ID=$(jq -r '.site_id' $CONFIG_FILE)
        DEPLOYMENT_ID=$(jq -r '.deployment_id' $CONFIG_FILE)
        terraform init -backend-config="bucket=$TERRAFORM_BACKEND_S3_BUCKET" -backend-config="key=$SITE_ID/aws/$DEPLOYMENT_ID/restore.tfstate" -backend-config="region=$AWS_DEFAULT_REGION"
        terraform apply -var-file $CONFIG_FILE -auto-approve

