apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    "helm.sh/hook": "pre-upgrade"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "4"
  labels:
    arcgis-helm/siteName: "{{ .Release.Name }}"
  name: "{{ .Release.Name }}-pre-upgrade-hook-job"
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        arcgis-helm/siteName: "{{ .Release.Name }}"
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
    spec:
      serviceAccountName: "{{ .Release.Name }}-pre-upgrade-hook-service-account"
      containers:
        - name: pre-upgrade-container
          image: {{ include "imagePath" ( dict "image" "enterprise-admin-tools" "global" . ) }}
          imagePullPolicy: Always
          command: [ '/arcgis/framework/helm/upgrade-from-helm.sh' ]
          resources:
            requests:
              cpu: "0.5"
              memory: "1Gi"
            limits:
              cpu: "1"
              memory: "2Gi"
          volumeMounts:
            - mountPath: /arcgisusr/user-inputs
              name: user-inputs
            - mountPath: /arcgistmp
              name: arcgistmp
      restartPolicy: Never
      terminationGracePeriodSeconds: 0
      volumes:
        - name: user-inputs
          secret:
            secretName: "{{ .Release.Name }}-pre-upgrade-hook-user-inputs-secret"
        - name: arcgistmp
          emptyDir: {}
      imagePullSecrets:
        - name: "{{ .Release.Name }}-pre-upgrade-hook-container-registry-secret"
