apiVersion: v1
kind: Secret
metadata:
  annotations:
    "helm.sh/hook": "pre-upgrade"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "-2"
  labels:
    arcgis-helm/siteName: "{{ .Release.Name }}"
  name: "{{ .Release.Name }}-pre-upgrade-hook-user-inputs-secret"
type: Opaque
stringData:
  upgrade-inputs.properties: {{ tpl ( .Files.Get "resources/upgrade.properties") . | b64enc }}
  license.file.json: {{ tpl ( .Files.Get .Values.upgrade.licenseFile ) . | b64enc }}
