name: server-linux-aws-destroy

on:
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TERRAFORM_BACKEND_S3_BUCKET: ${{ vars.TERRAFORM_BACKEND_S3_BUCKET }}
  AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
  ARCGIS_ONLINE_USERNAME: ${{ secrets.ARCGIS_ONLINE_USERNAME }}
  ARCGIS_ONLINE_PASSWORD: ${{ secrets.ARCGIS_ONLINE_PASSWORD }}
  PYTHONPATH: ${{ github.workspace }}/aws/scripts
  APPLICATION_CONFIG_FILE: ${{ github.workspace }}/config/aws/arcgis-server-linux/application.tfvars.json
  INFRASTRUCTURE_CONFIG_FILE: ${{ github.workspace }}/config/aws/arcgis-server-linux/infrastructure.tfvars.json

concurrency:
  group: ${{ github.ref_name }}

jobs:
  destroy:
    name: Destroy Deployment
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
      - name: Install boto3
        id: install-boto3
        run: pip install boto3
      - name: Destroy Application
        id: application-destroy
        working-directory: aws/arcgis-server-linux/application
        run: |
          SITE_ID=$(jq -r '.site_id' $APPLICATION_CONFIG_FILE)
          DEPLOYMENT_ID=$(jq -r '.deployment_id' $APPLICATION_CONFIG_FILE)
          terraform init -backend-config="bucket=$TERRAFORM_BACKEND_S3_BUCKET" -backend-config="key=$SITE_ID/aws/$DEPLOYMENT_ID/application.tfstate" -backend-config="region=$AWS_DEFAULT_REGION"
          terraform destroy -var-file $APPLICATION_CONFIG_FILE -var=arcgis_online_username=$ARCGIS_ONLINE_USERNAME -var=arcgis_online_password=$ARCGIS_ONLINE_PASSWORD -auto-approve
      - name: Destroy Infrastructure
        id: infrastructure-destroy
        working-directory: aws/arcgis-server-linux/infrastructure
        run: |
          SITE_ID=$(jq -r '.site_id' $INFRASTRUCTURE_CONFIG_FILE)
          DEPLOYMENT_ID=$(jq -r '.deployment_id' $INFRASTRUCTURE_CONFIG_FILE)
          terraform init -backend-config="bucket=$TERRAFORM_BACKEND_S3_BUCKET" -backend-config="key=$SITE_ID/aws/$DEPLOYMENT_ID/infrastructure.tfstate" -backend-config="region=$AWS_DEFAULT_REGION" 
          terraform destroy -var-file $INFRASTRUCTURE_CONFIG_FILE -auto-approve
