name: arcgis-enterprise-k8s-aws-destroy

on: 
  workflow_dispatch:
    inputs:
      delete_namespace:
        description: 'Delete namespace'
        type: boolean
        required: true
        default: false

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
  TERRAFORM_BACKEND_S3_BUCKET: ${{ vars.TERRAFORM_BACKEND_S3_BUCKET }}  
  AWS_MAX_ATTEMPTS: 400
  ORGANIZATION_CONFIG_FILE: ${{ github.workspace }}/config/aws/arcgis-enterprise-k8s/organization.tfvars.json
  INGRESS_CONFIG_FILE: ${{ github.workspace }}/config/aws/arcgis-enterprise-k8s/ingress.tfvars.json

concurrency:
  group: ${{ github.ref_name }}
  
jobs:
  destroy:
    name: arcgis-enterprise-k8s/destroy
    runs-on: ubuntu-latest
    outputs:
      alb_dns_name: ${{ steps.output.outputs.alb_dns_name }}
      arcgis_enterprise_manager_url: ${{ steps.output.outputs.arcgis_enterprise_manager_url }}
    defaults:
      run:
        working-directory: aws/arcgis-enterprise-k8s/organization
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
      - name: Link config directory
        id: symlink
        run: ln -s ${{ github.workspace }}/config ~/config
      - name: Update kubeconfig
        id: update-kubeconfig
        run: |
          SITE_ID=$(jq -r '.site_id' $ORGANIZATION_CONFIG_FILE)
          aws eks update-kubeconfig --region $AWS_DEFAULT_REGION --name $SITE_ID
      - name: Destroy Organization
        id: destroy-organization
        working-directory: aws/arcgis-enterprise-k8s/organization
        run: |
          SITE_ID=$(jq -r '.site_id' $ORGANIZATION_CONFIG_FILE)
          DEPLOYMENT_ID=$(jq -r '.deployment_id' $ORGANIZATION_CONFIG_FILE)
          terraform init -backend-config="bucket=$TERRAFORM_BACKEND_S3_BUCKET" -backend-config="key=$SITE_ID/aws/$DEPLOYMENT_ID/organization.tfstate" -backend-config="region=$AWS_DEFAULT_REGION" 
          terraform destroy -var-file $ORGANIZATION_CONFIG_FILE -auto-approve
      - name: Destroy Ingress
        id: destroy-ingress
        if: ${{ inputs.delete_namespace }} 
        working-directory: aws/arcgis-enterprise-k8s/ingress
        run: |
          SITE_ID=$(jq -r '.site_id' $INGRESS_CONFIG_FILE)
          DEPLOYMENT_ID=$(jq -r '.deployment_id' $INGRESS_CONFIG_FILE)
          terraform init -backend-config="bucket=$TERRAFORM_BACKEND_S3_BUCKET" -backend-config="key=$SITE_ID/aws/$DEPLOYMENT_ID/ingress.tfstate" -backend-config="region=$AWS_DEFAULT_REGION" 
          terraform destroy -var-file $INGRESS_CONFIG_FILE -auto-approve


