name: enterprise-k8s-aws-backup

on: 
  workflow_dispatch:
  # schedule:
  #   - cron: '0 0 * * *'
   
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
  CONFIG_FILE: ${{ github.workspace }}/config/aws/arcgis-enterprise-k8s/backup.vars.json

jobs:
  backup:
    name: Create Backup
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref_name }}
    - name: Create backup
      run: |
        SITE_ID=$(jq -r '.site_id' $CONFIG_FILE)
        DEPLOYMENT_ID=$(jq -r '.deployment_id' $CONFIG_FILE)
        STORE=$(jq -r '.store' $CONFIG_FILE)
        BACKUP=$(jq -r '.prefix' $CONFIG_FILE)-${{ github.run_number }}
        PASSCODE=$(jq -r '.passcode' $CONFIG_FILE)
        RETENTION=$(jq -r '.retention' $CONFIG_FILE)
        DESCRIPTION=$(jq -r '.description' $CONFIG_FILE)
        aws eks update-kubeconfig --region $AWS_DEFAULT_REGION --name $SITE_ID
        kubectl exec enterprise-admin-cli --namespace=$DEPLOYMENT_ID -- gis create-backup --store "$STORE" --backup "$BACKUP" --passcode "$PASSCODE" --description "$DESCRIPTION" --retention $RETENTION --wait
