name: enterprise-k8s-aws-ingress

on: 
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
  TERRAFORM_BACKEND_S3_BUCKET: ${{ vars.TERRAFORM_BACKEND_S3_BUCKET }}  
  AWS_MAX_ATTEMPTS: 400
  CONFIG_FILE: ${{ github.workspace }}/config/aws/arcgis-enterprise-k8s/ingress.tfvars.json

concurrency:
  group: ${{ github.ref_name }}
  
jobs:
  ingress:
    name: Ingress Controller
    runs-on: ubuntu-latest
    outputs:
      alb_dns_name: ${{ steps.output.outputs.alb_dns_name }}
    defaults:
      run:
        working-directory: aws/arcgis-enterprise-k8s/ingress
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
      - name: Update kubeconfig
        id: update-kubeconfig
        run: |
          SITE_ID=$(jq -r '.site_id' $CONFIG_FILE)
          aws eks update-kubeconfig --region $AWS_DEFAULT_REGION --name $SITE_ID
      - name: Run Terraform
        id: terraform
        run: |
          SITE_ID=$(jq -r '.site_id' $CONFIG_FILE)
          DEPLOYMENT_ID=$(jq -r '.deployment_id' $CONFIG_FILE)
          terraform init -backend-config="bucket=$TERRAFORM_BACKEND_S3_BUCKET" -backend-config="key=$SITE_ID/aws/$DEPLOYMENT_ID/ingress.tfstate" -backend-config="region=$AWS_DEFAULT_REGION" 
          terraform apply -var-file $CONFIG_FILE -auto-approve 
      - name: Terraform Output
        id: output  
        run: |
          echo alb_dns_name=$(terraform output alb_dns_name) >> $GITHUB_OUTPUT
         
