---
# This playbook installs ArcGIS Server patches on the target machine.

- name: Install ArcGIS Server patches
  hosts: all
  vars:
    install_dir: '/opt' 
    patches_directory: '/opt/software/archives/patches'
    run_as_user: 'arcgis'
    arcgis_server_patches: []
  become: true
  tasks:
    - name: Stop arcgisserver service
      ansible.builtin.service:
        name: arcgisserver
        state: stopped
    - name: Install ArcGIS Server patches 
      become: true
      become_user: '{{ run_as_user }}'
      vars:
        ansible_aws_ssm_timeout: 3600
      arcgis.common.install_patches:
        patch: '{{ item }}'
        dir: '{{ patches_directory }}'
        log: '{{ install_dir }}/arcgis/server/.ESRI_S_PATCH_LOG'
        product: 'server'
      loop: '{{ arcgis_server_patches }}' 
    - name: Start arcgisserver service
      ansible.builtin.service:
        name: arcgisserver
        state: started

