---
# This playbook authorizes ArcGIS Server on the target machine, creates 
# an ArcGIS Server site, and sets the site's system properties.

- name: Configure ArcGIS Server
  hosts: all
  vars:
    run_as_user: 'arcgis'
    install_dir: '/opt'
    system_properties: {}
    services_dir_enabled: true
  tasks:
    - name: Authorize ArcGIS Server
      become: true
      become_user: '{{ run_as_user }}'
      vars:
        ansible_aws_ssm_timeout: 600
      ansible.builtin.command:
        argv:
          - '{{ install_dir }}/arcgis/server/tools/authorizeSoftware'
          - -f
          - '{{ authorization_file }}'
      register: authorize_software
      changed_when: authorize_software.rc == 0
    - name: Create ArcGIS Server site
      vars:
        ansible_aws_ssm_timeout: 3600
      no_log: false
      arcgis.server.create_site:
        server_url: 'https://localhost:6443/arcgis'
        admin_username: '{{ admin_username }}'
        admin_password: '{{ admin_password }}'
        directories_root: '{{ directories_root }}'
        config_store_type: '{{ config_store_type }}'
        config_store_connection_string: '{{ config_store_connection_string }}'
        config_store_connection_secret: ''
        log_level: '{{ log_level }}'
        log_dir: '{{ log_dir }}'
        max_log_file_age: '{{ max_log_file_age }}'
    - name: Set ArcGIS Server system properties
      vars:
        ansible_aws_ssm_timeout: 600
      no_log: false
      arcgis.server.set_system_properties:
        server_url: 'https://localhost:6443/arcgis'
        admin_username: '{{ admin_username }}'
        admin_password: '{{ admin_password }}'
        system_properties: '{{ system_properties }}'
        services_dir_enabled: '{{ services_dir_enabled }}'
