namespace: arcgis

name: server

version: 0.1.0

readme: README.md

authors:
- Pavel Bobov <pbobov@esri.com>

description: Modules and playbooks used to install and configure ArcGIS Server

license:
- Apache-2.0

license_file: ''

tags: ['arcgis', 'arcgis-server']

dependencies: {}

repository: https://github.com/Esri/arcgis-gitops

documentation: https://github.com/Esri/arcgis-gitops

homepage: https://github.com/Esri/arcgis-gitops

issues: https://github.com/Esri/arcgis-gitops/issues

build_ignore: []
