name: arcgis-site-k8s-cluster-aws-destroy

on: 
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TERRAFORM_BACKEND_S3_BUCKET: ${{ vars.TERRAFORM_BACKEND_S3_BUCKET }}
  AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
  CONFIG_FILE: ${{ github.workspace }}/config/aws/arcgis-site-core/k8s-cluster.tfvars.json

concurrency:
  group: ${{ github.ref_name }}
  
jobs:
  k8s-cluster-destroy:
    name: Destroy K8s Cluster
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: aws/arcgis-site-core/k8s-cluster
    permissions:
      contents: read
      pull-requests: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref_name }}
    - name: Terraform Init
      id: init
      run: |
        SITE_ID=$(jq -r '.site_id' $CONFIG_FILE)
        terraform init -backend-config="bucket=$TERRAFORM_BACKEND_S3_BUCKET" -backend-config="key=$SITE_ID/aws/k8s-cluster.tfstate" -backend-config="region=$AWS_DEFAULT_REGION" 
    - name: Terraform Destroy
      id: destroy
      run: terraform destroy -var-file $CONFIG_FILE -auto-approve

