name: site-core-aws

on: 
  workflow_dispatch:
    inputs:
      terraform_command:
        description: 'Terraform Command'
        type: choice
        options:
        - apply
        - plan

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TERRAFORM_BACKEND_S3_BUCKET: ${{ vars.TERRAFORM_BACKEND_S3_BUCKET }}
  AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
  CONFIG_FILE: ${{ github.workspace }}/config/aws/arcgis-site-core/infrastructure-core.tfvars.json

concurrency:
  group: ${{ github.ref_name }}

jobs:
  infrastructure_core:
    name: Core AWS Infrastructure
    runs-on: ubuntu-latest
    outputs:
      vpc_id: ${{ steps.output.outputs.vpc_id }}
    defaults:
      run:
        working-directory: aws/arcgis-site-core/infrastructure-core
    permissions:
      contents: read
      pull-requests: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref_name }}
    - name: Terraform Init
      id: terraform-init
      run: |
        SITE_ID=$(jq -r '.site_id' $CONFIG_FILE)
        terraform init -backend-config="bucket=$TERRAFORM_BACKEND_S3_BUCKET" -backend-config="key=$SITE_ID/aws/infrastructure-core.tfstate" -backend-config="region=$AWS_DEFAULT_REGION" 
    - name: Terraform Apply
      id: terraform-apply
      if: github.event.inputs.terraform_command == 'apply'
      run: terraform apply -var-file $CONFIG_FILE -auto-approve
    - name: Terraform Plan
      id: terraform-plan
      if: github.event.inputs.terraform_command == 'plan'
      run: terraform plan -var-file $CONFIG_FILE
    - name: Terraform Output
      id: terraform-output
      run: |
        echo vpc_id=$(terraform output -json | jq -r .vpc_id.value) >> $GITHUB_OUTPUT
