name: site-k8s-cluster-aws

on: 
  workflow_dispatch:
    inputs:
      terraform_command:
        description: 'Terraform Command'
        type: choice
        options:
        - apply
        - plan

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TERRAFORM_BACKEND_S3_BUCKET: ${{ vars.TERRAFORM_BACKEND_S3_BUCKET }}
  AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
  CONFIG_FILE: ${{ github.workspace }}/config/aws/arcgis-site-core/k8s-cluster.tfvars.json

concurrency:
  group: ${{ github.ref_name }}
  
jobs:
  k8s-cluster:
    name: Create K8s cluster
    runs-on: ubuntu-latest
    outputs:
      cluster_name: ${{ steps.output.outputs.cluster_name }}
      cluster_endpoint: ${{ steps.output.outputs.cluster_endpoint }}
    defaults:
      run:
        working-directory: aws/arcgis-site-core/k8s-cluster
    permissions:
      contents: read
      pull-requests: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref_name }}
    - name: Terraform Init
      id: init
      run: |
        SITE_ID=$(jq -r '.site_id' $CONFIG_FILE)
        terraform init -backend-config="bucket=$TERRAFORM_BACKEND_S3_BUCKET" -backend-config="key=$SITE_ID/aws/k8s-cluster.tfstate" -backend-config="region=$AWS_DEFAULT_REGION" 
    - name: Terraform Apply
      id: apply
      if: github.event.inputs.terraform_command == 'apply'
      run: terraform apply -var-file $CONFIG_FILE -auto-approve
    - name: Terraform Plan
      id: plan
      if: github.event.inputs.terraform_command == 'plan'
      run: terraform plan -var-file $CONFIG_FILE
    - name: Test EKS cluster access
      id: test
      run: |
        echo "Test"
        SITE_ID=$(jq -r '.site_id' $CONFIG_FILE)
        aws eks update-kubeconfig --region $AWS_DEFAULT_REGION --name $SITE_ID
        kubectl get nodes
    - name: Terraform Output
      id: output
      run: |
        echo cluster_name=$(terraform output cluster_name) >> $GITHUB_OUTPUT
        echo cluster_endpoint=$(terraform output cluster_endpoint) >> $GITHUB_OUTPUT
  