{{- if gt (len .Release.Name) 7 -}}
{{- printf "\n\nERROR: The relase name \"%s\" should be 7 characters or less\n\n" .Release.Name | fail -}}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "-2"
  labels:
    arcgis-helm/siteName: "{{ .Release.Name }}"
  name: "{{ .Release.Name }}-pre-install-hook-user-inputs-secret"
type: Opaque
stringData:
  deploy-inputs.properties: {{ tpl ( .Files.Get "resources/deploy.properties") . | b64enc }}
  configure.properties: {{ tpl ( .Files.Get "resources/configure.properties") . | b64enc }}
  {{- if .Values.configure.enabled }}
  license.file.json: {{ tpl ( .Files.Get .Values.configure.licenseFile ) . | b64enc }}
  {{- if .Values.configure.cloudConfigJsonFilename }}
  cloud.config.json: {{ tpl ( .Files.Get .Values.configure.cloudConfigJsonFilename ) . | b64enc }}
  {{- end }}
  {{- end }}
