
configure:

  # ------------------------------------
  # ARCHITECTURE PROFILE
  #
  # Specify the deployment profile you wish to use.
  # ------------------------------------
  #
  # Profiles
  # ------------------------------------
  # development
  # standard-availability
  # enhanced-availability
  systemArchProfile: development


  # ------------------------------------
  # LICENSE PROPERTIES
  #
  # NOTE: Helm does not support accessing files from outside the Chart folder.
  # For this reason you need to copy your ArcGIS Enterprise on Kubernetes 
  # license file to the ./user-inputs/ folder and reference that file here.
  # ------------------------------------
  licenseFile: user-inputs/my-license-file.json

  # Specify the user type ID for the primary administrator.
  # Examples of user type IDs along with their user type below:
  #
  # User type                   Type Id
  # --------------------------|-----------------------
  # Creator                   | creatorUT
  # GIS Professional Basic    | GISProfessionalBasicUT
  # GIS Professional Standard | GISProfessionalStdUT
  # GIS Professional Advanced | GISProfessionalAdvUT
  licenseTypeId: creatorUT


  # ------------------------------------
  # ADMINISTRATOR ACCOUNT PROPERTIES
  #
  # The configure.admin.username must be a minimum of 6 characters and can only contain the following,
  # numbers 0-9, ASCII letters a-z, A-Z, at symbol (@), dash (-), period (.), and underscore (_).
  #
  # The configure.admin.password must be a minimum of 8 characters and must contain at least one letter
  # (A-Z, a-z), one number (0-9) and a special character.
  #
  # ------------------------------------
  admin:
    username:
    password:
    email:
    firstName:
    lastName:


  # Specify the security question and answer for the primary administrator.
  # Questions along with their indexes shown below:
  #
  # Index   Question
  # ----- | -----------------------------------------------------
  # 1     | What city were you born in?
  # 2     | What was your high school mascot?
  # 3     | What is your mother's maiden name?
  # 4     | What was the make of your first car?
  # 5     | What high school did you go to?
  # 6     | What is the last name of your best friend?
  # 7     | What is the middle name of your youngest sibling?
  # 8     | What is the name of the street on which you grew up?
  # 9     | What is the name of your favorite fictional character?
  # 10    | What is the name of your favorite pet?
  # 11    | What is the name of your favorite restaurant?
  # 12    | What is the title of your favorite book?
  # 13    | What is your dream job?
  # 14    | Where did you go on your first date?

  # Match this number with the questions above (between 1 and 14).
  securityQuestionIndex: 
  securityQuestionAnswer: 


  # ------------------------------------
  # CLOUD CONFIG JSON FILENAME
  #
  # Use one of these json templates in arcgis-enterprise/resources/templates
  # to create a cloud configuration file which contains your configuration info:
  #
  #  cloud-config-amazon-s3-access-key.json.template
  #  cloud-config-amazon-s3-iam-role.json.template
  #  cloud-config-azure-blob-managed-identity.json.template
  #  cloud-config-azure-blob-storage-account-key.json.template
  #  cloud-config-google-cloud-hmac-key.json.template
  #
  # Copy one these templates locally (remove the .template suffix) and add your
  # cloud configuration info.
  #
  # Then set cloudConfigJsonFilename to the full path of this file. Since Helm
  # cannot reference files outside the chart folder you should put this file
  # in the ./user-inputs/ folder and reference that file here.
  #
  # This file can be deleted after a successful configure is completed.
  cloudConfigJsonFilename:


  # ------------------------------------
  # LOG SETTINGS
  #
  # Valid values:
  #
  #     SEVERE |  WARNING | INFO | FINE | VERBOSE | DEBUG
  #
  # The log level at which logs will be recorded during configuration.
  # If no log level is specified, the default WARNING level will be used
  # once the organization is configured. The log level can be changed
  # after configuration using the edit operation.
  #
  # NOTE: Leave blank if you do not want wish to change the log setting.
  logSetting: 


  # ------------------------------------
  # LOG RETENTION MAX DAYS
  #
  # Number of days logs will be retained by the organization.
  #
  # Valid values:
  #
  #     An integer value between 1 and 999.
  #
  logRetentionMaxDays: 60


  # ------------------------------------
  # STORAGE PROPERTIES
  # ------------------------------------
  #
  # Storage type can be "STATIC" or "DYNAMIC". By default, the type is set to
  # DYNAMIC.
  #
  #  - For dynamic:
  #     - Storage class names are mandatory and must already exist in the cluster.
  #     - Labels are optional
  #  - For static:
  #     - Labels are mandatory.
  #     - Persistent Volume Claims use label selectors (matchLabels).
  #     - Persistent Volumes must match the label selector to be bound to the claim.
  #
  # - Size and type are mandatory for both static and dynamic storage.
  # - Values are case sensitive.
  # - For storage labels, use "key:value" syntax. For example:
  #
  #     label1: arcgis/tier:storage
  #     label2: arcgis/app:postgres

  storage:

    # Relational Store
    relational:
      type: DYNAMIC
      size: 16Gi
      class:
      label1:
      label2:

    # Object Store
    object:
      type: DYNAMIC
      size: 32Gi
      class:
      label1:
      label2:
      
    # In-Memory Store
    memory:
      type: DYNAMIC
      size: 16Gi
      class:
      label1:
      label2:

    # Queue Store
    queue:
      type: DYNAMIC
      size: 16Gi
      class:
      label1:
      label2:

    # Spatiotemporal and Index Store
    indexer:
      type: DYNAMIC
      size: 16Gi
      class:
      label1:
      label2:

    # Item Packages
    sharing:
      type: DYNAMIC
      size: 16Gi
      class:
      label1:
      label2:

    # Prometheus (metrics api)
    prometheus:
      type: DYNAMIC
      size: 30Gi
      class:
      label1:
      label2:


# END
