name: validate-settings-aws

on: 
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
  TERRAFORM_BACKEND_S3_BUCKET: ${{ vars.TERRAFORM_BACKEND_S3_BUCKET }}
  ARCGIS_ONLINE_USERNAME: ${{ secrets.ARCGIS_ONLINE_USERNAME }}
  ARCGIS_ONLINE_PASSWORD: ${{ secrets.ARCGIS_ONLINE_PASSWORD }}
  CONTAINER_REGISTRY_USER: ${{ secrets.CONTAINER_REGISTRY_USER }}
  CONTAINER_REGISTRY_PASSWORD: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
  PYTHONPATH: ${{ github.workspace }}/aws/scripts

jobs:
  validate_settings_aws:
    name: Validate GitHub Actions secrets and variables
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref_name }}
    - name: Install boto3
      id: install-boto3
      run: pip install boto3    
    - name: Test AWS credentials
      id: test-aws-credentials
      run: python -m test_aws_credentials -b $TERRAFORM_BACKEND_S3_BUCKET
    - name: Test ArcGIS Online credentials
      id: test-arcgis-online-credentials
      run: python -m token_service_client 
    - name: Test Docker Hub credentials
      if: ${{ env.CONTAINER_REGISTRY_USER }} 
      id: test-docker-hub-credentials
      run: echo $CONTAINER_REGISTRY_PASSWORD | docker login --username $CONTAINER_REGISTRY_USER --password-stdin
